version: '2'

linters:
  exclusions:
    rules:
      - path: _test.go
        linters:
          - dupl
          - goconst
      - source: "^\\s*defer\\s+"
        linters:
          - errcheck
          - staticcheck

  settings:
    godoclint:
      disable:
        - start-with-name

    errcheck:
      exclude-functions:
        - fmt.Fprint
        - fmt.Fprintln

    exhaustive:
      default-signifies-exhaustive: true

    lll:
      line-length: 120

severity:
  default: error
