version: 2

project_name: stamp

before:
  hooks:
    - go mod tidy
    - go generate ./...
    - ./bin/build-completions.sh {{ .ProjectName }}
    - ./bin/build-manpages.sh {{ .ProjectName }}
    - ./bin/build-schema.sh {{ .ProjectName }}
    - ./bin/build-docs.sh {{ .ProjectName }}

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    # `flags`, `ldflags`, and `mod_timestamp` are configured for reproducible builds.
    # See: https://goreleaser.com/customization/builds/#reproducible-builds
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.CommitDate}}
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - id: default
    builds_info:
      group: root
      owner: root
    files:
      - README.md
      - LICENSE
      - src: build/completions/*
        dst: completions
        strip_parent: true
      - src: build/manpages/*
        dst: manpages
        strip_parent: true
      - src: build/schemas/*
        dst: schemas
        strip_parent: true
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

brews:
  - repository:
      owner: twelvelabs
      name: homebrew-tap
      branch: main
    directory: Formula
    homepage: "https://github.com/twelvelabs/stamp"
    description: "A project and file scaffolding tool"
    license: "MIT"
    install: |-
      bin.install "stamp"
      bash_completion.install "completions/stamp.bash" => "stamp"
      zsh_completion.install "completions/stamp.zsh" => "_stamp"
      fish_completion.install "completions/stamp.fish"
      man1.install "manpages/stamp.1.gz"
    test: |
      system "#{bin}/stamp --version"

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  use: github
  sort: asc
  groups:
    - title: New features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: Bug fixes
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: Other work
      order: 99

dockers:
  - image_templates:
      - "ghcr.io/twelvelabs/{{ .ProjectName }}:{{ .Tag }}-amd64"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/amd64"
    goarch: amd64
    use: buildx

  - image_templates:
      - "ghcr.io/twelvelabs/{{ .ProjectName }}:{{ .Tag }}-arm64"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/arm64"
    goarch: arm64
    use: buildx

docker_manifests:
  - name_template: "ghcr.io/twelvelabs/{{ .ProjectName }}:{{ .Tag }}"
    image_templates:
      - "ghcr.io/twelvelabs/{{ .ProjectName }}:{{ .Tag }}-amd64"
      - "ghcr.io/twelvelabs/{{ .ProjectName }}:{{ .Tag }}-arm64"

  - name_template: "ghcr.io/twelvelabs/{{ .ProjectName }}:latest"
    image_templates:
      - "ghcr.io/twelvelabs/{{ .ProjectName }}:{{ .Tag }}-amd64"
      - "ghcr.io/twelvelabs/{{ .ProjectName }}:{{ .Tag }}-arm64"

# Temporarily disabling gomod.proxy until we can update mergo.
# See goreleaser output:
# • your go.mod file has replace directive in it, and go mod proxying is enabled -
#   this does not work, and you need to either disable it or remove the replace directive
# • the offending line is replace github.com/imdario/mergo => dario.cat/mergo v0.3.16
# gomod:
#   proxy: true

report_sizes: true

snapshot:
  version_template: "{{ incpatch .Version }}-next" # cspell: disable-line
