excludes:
  - dist/**
  - .cspellcache
  - coverage.*
  - go.{mod,sum}
  - TODO.md
processors:
  - preset: cspell
  - preset: gitleaks
  - preset: gofmt
  - preset: golangci-lint
  - preset: markdownlint
  - preset: shellcheck
    includes:
      - "**/*.sh"
      - "githooks/*"
  - preset: shfmt
    includes:
      - "**/*.sh"
      - "githooks/*"
