#!/usr/bin/env bash
set -o errexit -o errtrace -o nounset -o pipefail

# Run all staged paths through stylist.
# - `readarray` syntax re: https://www.shellcheck.net/wiki/SC2046
# - `diff-filter=d` excludes deleted paths.
read -ra staged_paths < <(git diff --diff-filter=d --name-only --staged | xargs)
if [ ! ${#staged_paths[@]} -eq 0 ]; then
    stylist check "${staged_paths[@]}" # expand array as args
fi
