// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package modify

import (
	"fmt"
	"strings"
)

const (
	// ActionAppend is a Action of type append.
	ActionAppend Action = "append"
	// ActionPrepend is a Action of type prepend.
	ActionPrepend Action = "prepend"
	// ActionReplace is a Action of type replace.
	ActionReplace Action = "replace"
	// ActionDelete is a Action of type delete.
	ActionDelete Action = "delete"
)

var ErrInvalidAction = fmt.Errorf("not a valid Action, try [%s]", strings.Join(_ActionNames, ", "))

var _ActionNames = []string{
	string(ActionAppend),
	string(ActionPrepend),
	string(ActionReplace),
	string(ActionDelete),
}

// ActionNames returns a list of possible string values of Action.
func ActionNames() []string {
	tmp := make([]string, len(_ActionNames))
	copy(tmp, _ActionNames)
	return tmp
}

// String implements the Stringer interface.
func (x Action) String() string {
	return string(x)
}

// String implements the Stringer interface.
func (x Action) IsValid() bool {
	_, err := ParseAction(string(x))
	return err == nil
}

var _ActionValue = map[string]Action{
	"append":  ActionAppend,
	"prepend": ActionPrepend,
	"replace": ActionReplace,
	"delete":  ActionDelete,
}

// ParseAction attempts to convert a string to a Action.
func ParseAction(name string) (Action, error) {
	if x, ok := _ActionValue[name]; ok {
		return x, nil
	}
	return Action(""), fmt.Errorf("%s is %w", name, ErrInvalidAction)
}

// MarshalText implements the text marshaller method.
func (x Action) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *Action) UnmarshalText(text []byte) error {
	tmp, err := ParseAction(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

const (
	// MergeTypeConcat is a MergeType of type concat.
	MergeTypeConcat MergeType = "concat"
	// MergeTypeUpsert is a MergeType of type upsert.
	MergeTypeUpsert MergeType = "upsert"
	// MergeTypeReplace is a MergeType of type replace.
	MergeTypeReplace MergeType = "replace"
)

var ErrInvalidMergeType = fmt.Errorf("not a valid MergeType, try [%s]", strings.Join(_MergeTypeNames, ", "))

var _MergeTypeNames = []string{
	string(MergeTypeConcat),
	string(MergeTypeUpsert),
	string(MergeTypeReplace),
}

// MergeTypeNames returns a list of possible string values of MergeType.
func MergeTypeNames() []string {
	tmp := make([]string, len(_MergeTypeNames))
	copy(tmp, _MergeTypeNames)
	return tmp
}

// String implements the Stringer interface.
func (x MergeType) String() string {
	return string(x)
}

// String implements the Stringer interface.
func (x MergeType) IsValid() bool {
	_, err := ParseMergeType(string(x))
	return err == nil
}

var _MergeTypeValue = map[string]MergeType{
	"concat":  MergeTypeConcat,
	"upsert":  MergeTypeUpsert,
	"replace": MergeTypeReplace,
}

// ParseMergeType attempts to convert a string to a MergeType.
func ParseMergeType(name string) (MergeType, error) {
	if x, ok := _MergeTypeValue[name]; ok {
		return x, nil
	}
	return MergeType(""), fmt.Errorf("%s is %w", name, ErrInvalidMergeType)
}

// MarshalText implements the text marshaller method.
func (x MergeType) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *MergeType) UnmarshalText(text []byte) error {
	tmp, err := ParseMergeType(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}
