---
name: build

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write # if pushing docker images

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # pin@v4.1.1
        with:
          fetch-depth: 0
          # Need a PAT so that `make release-tag` will trigger the release workflow.
          # See: https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow
          token: ${{ github.ref_name == 'main' && secrets.GH_PAT || secrets.GITHUB_TOKEN }}

      - name: Set up Homebrew
        uses: homebrew/actions/setup-homebrew@f8b224a6d5e4f1668351c7e7e7c0c1c10e228294 # pin@master

      - name: Set up Go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # pin@v4.1.0
        with:
          go-version-file: go.mod

      - name: Install dependencies
        run: make setup

      - name: Build
        run: make build

      - name: Lint
        run: make lint

      - name: Test
        run: make test

      - name: Coverage
        uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d # pin@v3.1.4

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@82a020f1f7f605c65dd2449b392a52c3fcfef7ef # pin@v6.0.0
        if: github.ref_name == 'main'
        with:
          gpg_private_key: ${{ secrets.GH_COMMIT_SIGNING_KEY }}
          passphrase: ${{ secrets.GH_COMMIT_SIGNING_PASS }}
          git_config_global: true
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_tag_gpgsign: true
          git_push_gpgsign: false

      - name: Create release tag
        if: github.ref_name == 'main'
        run: make release-tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
